// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordgetter.proto

/*
Package recordgetter is a generated protocol buffer package.

It is generated from these files:
	recordgetter.proto

It has these top-level messages:
	Empty
	State
	GetRecordRequest
*/
package recordgetter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import recordcollection "github.com/brotherlogic/recordcollection/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type State struct {
	CurrentPick *recordcollection.Record `protobuf:"bytes,1,opt,name=current_pick,json=currentPick" json:"current_pick,omitempty"`
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *State) GetCurrentPick() *recordcollection.Record {
	if m != nil {
		return m.CurrentPick
	}
	return nil
}

type GetRecordRequest struct {
	Refresh bool `protobuf:"varint,1,opt,name=refresh" json:"refresh,omitempty"`
}

func (m *GetRecordRequest) Reset()                    { *m = GetRecordRequest{} }
func (m *GetRecordRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRecordRequest) ProtoMessage()               {}
func (*GetRecordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetRecordRequest) GetRefresh() bool {
	if m != nil {
		return m.Refresh
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "recordgetter.Empty")
	proto.RegisterType((*State)(nil), "recordgetter.State")
	proto.RegisterType((*GetRecordRequest)(nil), "recordgetter.GetRecordRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RecordGetter service

type RecordGetterClient interface {
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*recordcollection.Record, error)
	Listened(ctx context.Context, in *recordcollection.Record, opts ...grpc.CallOption) (*recordcollection.Record, error)
	Force(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type recordGetterClient struct {
	cc *grpc.ClientConn
}

func NewRecordGetterClient(cc *grpc.ClientConn) RecordGetterClient {
	return &recordGetterClient{cc}
}

func (c *recordGetterClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*recordcollection.Record, error) {
	out := new(recordcollection.Record)
	err := grpc.Invoke(ctx, "/recordgetter.RecordGetter/GetRecord", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordGetterClient) Listened(ctx context.Context, in *recordcollection.Record, opts ...grpc.CallOption) (*recordcollection.Record, error) {
	out := new(recordcollection.Record)
	err := grpc.Invoke(ctx, "/recordgetter.RecordGetter/Listened", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordGetterClient) Force(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/recordgetter.RecordGetter/Force", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RecordGetter service

type RecordGetterServer interface {
	GetRecord(context.Context, *GetRecordRequest) (*recordcollection.Record, error)
	Listened(context.Context, *recordcollection.Record) (*recordcollection.Record, error)
	Force(context.Context, *Empty) (*Empty, error)
}

func RegisterRecordGetterServer(s *grpc.Server, srv RecordGetterServer) {
	s.RegisterService(&_RecordGetter_serviceDesc, srv)
}

func _RecordGetter_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordGetterServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordgetter.RecordGetter/GetRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordGetterServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordGetter_Listened_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(recordcollection.Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordGetterServer).Listened(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordgetter.RecordGetter/Listened",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordGetterServer).Listened(ctx, req.(*recordcollection.Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordGetter_Force_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordGetterServer).Force(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordgetter.RecordGetter/Force",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordGetterServer).Force(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecordGetter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recordgetter.RecordGetter",
	HandlerType: (*RecordGetterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecord",
			Handler:    _RecordGetter_GetRecord_Handler,
		},
		{
			MethodName: "Listened",
			Handler:    _RecordGetter_Listened_Handler,
		},
		{
			MethodName: "Force",
			Handler:    _RecordGetter_Force_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordgetter.proto",
}

func init() { proto.RegisterFile("recordgetter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4f, 0xc3, 0x50,
	0x0c, 0x84, 0xd5, 0x21, 0xb4, 0xb8, 0x19, 0x90, 0x59, 0xa2, 0x0c, 0x08, 0x65, 0x62, 0x40, 0x89,
	0x28, 0x23, 0x12, 0x13, 0xa1, 0x0b, 0x03, 0x0a, 0x3f, 0x00, 0x11, 0xd7, 0x24, 0x4f, 0x4d, 0xe3,
	0xe0, 0x38, 0x03, 0xff, 0x90, 0x9f, 0x85, 0xf4, 0x52, 0x10, 0xa5, 0x94, 0xf1, 0xdd, 0xbb, 0xfb,
	0x74, 0x3e, 0x40, 0x65, 0x12, 0x5d, 0x55, 0x6c, 0xc6, 0x9a, 0x76, 0x2a, 0x26, 0x18, 0xfe, 0xd4,
	0xe2, 0xbc, 0x72, 0x56, 0x0f, 0x65, 0x4a, 0xb2, 0xc9, 0x4a, 0x15, 0xab, 0x59, 0x1b, 0xa9, 0x1c,
	0x65, 0xa3, 0x8b, 0xa4, 0x69, 0x98, 0xcc, 0x49, 0x9b, 0xf9, 0xf4, 0x9e, 0x3c, 0x42, 0x93, 0x29,
	0x04, 0xf9, 0xa6, 0xb3, 0xf7, 0xe4, 0x0e, 0x82, 0x27, 0x7b, 0x31, 0xc6, 0x1b, 0x08, 0x69, 0x50,
	0xe5, 0xd6, 0x9e, 0x3b, 0x47, 0xeb, 0x68, 0x72, 0x3e, 0xb9, 0x98, 0x2f, 0xa2, 0x74, 0x0f, 0x50,
	0x78, 0xa1, 0x98, 0x6f, 0xdd, 0x8f, 0x8e, 0xd6, 0xc9, 0x25, 0x9c, 0x2c, 0xd9, 0xb6, 0x3f, 0xfc,
	0x36, 0x70, 0x6f, 0x18, 0xc1, 0x54, 0xf9, 0x55, 0xb9, 0xaf, 0x3d, 0x6b, 0x56, 0x7c, 0x3d, 0x17,
	0x1f, 0x13, 0x08, 0x47, 0xef, 0xd2, 0x1f, 0x85, 0x39, 0x1c, 0x7f, 0xc7, 0xf1, 0x2c, 0xdd, 0x19,
	0xe1, 0x37, 0x37, 0x3e, 0x58, 0x09, 0x6f, 0x61, 0xf6, 0xe0, 0x7a, 0xe3, 0x96, 0x57, 0x78, 0xd0,
	0xf5, 0x4f, 0xfe, 0x0a, 0x82, 0x7b, 0x51, 0x62, 0x3c, 0xdd, 0xad, 0xe0, 0x97, 0x8a, 0xff, 0x12,
	0xcb, 0x23, 0x3f, 0xe7, 0xf5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0x7a, 0xc3, 0xf3, 0xb9,
	0x01, 0x00, 0x00,
}
